### 経験値を加算する
POST http://localhost:3000/api/exp_status
Content-Type: application/json

{
  "userId": 24,
  "difficultyLevel": 1
}

### ユーザーのステータスを取得する
GET http://localhost:3000/api/9/getstatus


### ユーザー登録
POST http://localhost:3000/api/register
Content-Type: application/json

{
  "username": "takuma",
  "email": "mitimiti@gmail.com",
  "password": "mitimiti"
}